export const userSource = [
  { value: 'user', label: '用户' },
  { value: 'admin', label: '管理员' },
  { value: 'editor', label: '编辑' },
];

export const abilitySource = [
  { label: '基础科学',
    children: [
      { value: 1001, label: '数学' },
      { value: 1002, label: '生物学' },
      { value: 1003, label: '天文学' },
      { value: 1004, label: '物理学' },
      { value: 1005, label: '力学' },
    ] },
  { label: '工程科技',
    children: [
      { value: 2001, label: '化学' },
      { value: 2002, label: '无机化工' },
      { value: 2003, label: '有机化工' },
      { value: 2004, label: '矿业工程' },
      { value: 2005, label: '冶金工业' },
    ] },
  { label: '农业科技',
    children: [
      { value: 3001, label: '园艺' },
      { value: 3002, label: '林业' },
      { value: 3003, label: '农艺学' },
      { value: 3004, label: '农业工程' },
      { value: 3005, label: '水产与渔业' },
    ] },
  { label: '医药卫生科技',
    children: [
      { value: 4001, label: '中医学' },
      { value: 4002, label: '中药学' },
      { value: 4003, label: '临床医学' },
      { value: 4004, label: '基础医学' },
      { value: 4005, label: '军事医学' },
    ] },
  { label: '哲学与人文科学',
    children: [
      { value: 5001, label: '文学' },
      { value: 5002, label: '音乐舞蹈' },
      { value: 5003, label: '地理' },
      { value: 5004, label: '文化' },
      { value: 5005, label: '考古' },
    ] },
  { label: '社会科学',
    children: [
      { value: 6001, label: '马克思主义' },
      { value: 6002, label: '中国共产党' },
      { value: 6003, label: '军事' },
      { value: 6004, label: '公安' },
      { value: 6005, label: '刑法' },
    ] },
  { label: '信息科技',
    children: [
      { value: 7001, label: '通信技术' },
      { value: 7002, label: '互联网技术' },
      { value: 7003, label: '计算机硬件' },
      { value: 7004, label: '无线电' },
      { value: 7005, label: '新闻与传媒' },
    ] },
  { label: '经济与管理科学',
    children: [
      { value: 8001, label: '农业经济' },
      { value: 8002, label: '工业经济' },
      { value: 8003, label: '文化经济' },
      { value: 8004, label: '金融' },
      { value: 8005, label: '证券' },
    ] },
];

export const abilityTags = [
  { value: 1001, label: '数学' },
  { value: 1002, label: '生物学' },
  { value: 1003, label: '天文学' },
  { value: 1004, label: '物理学' },
  { value: 1005, label: '力学' },
  { value: 2001, label: '化学' },
  { value: 2002, label: '无机化工' },
  { value: 2003, label: '有机化工' },
  { value: 2004, label: '矿业工程' },
  { value: 2005, label: '冶金工业' },
  { value: 3001, label: '园艺' },
  { value: 3002, label: '林业' },
  { value: 3003, label: '农艺学' },
  { value: 3004, label: '农业工程' },
  { value: 3005, label: '水产与渔业' },
  { value: 4001, label: '中医学' },
  { value: 4002, label: '中药学' },
  { value: 4003, label: '临床医学' },
  { value: 4004, label: '基础医学' },
  { value: 4005, label: '军事医学' },
  { value: 5001, label: '文学' },
  { value: 5002, label: '音乐舞蹈' },
  { value: 5003, label: '地理' },
  { value: 5004, label: '文化' },
  { value: 5005, label: '考古' },
  { value: 6001, label: '马克思主义' },
  { value: 6002, label: '中国共产党' },
  { value: 6003, label: '军事' },
  { value: 6004, label: '公安' },
  { value: 6005, label: '刑法' },
  { value: 7001, label: '通信技术' },
  { value: 7002, label: '互联网技术' },
  { value: 7003, label: '计算机硬件' },
  { value: 7004, label: '无线电' },
  { value: 7005, label: '新闻与传媒' },
  { value: 8001, label: '农业经济' },
  { value: 8002, label: '工业经济' },
  { value: 8003, label: '文化经济' },
  { value: 8004, label: '金融' },
  { value: 8005, label: '证券' },
];

export const contentList = [
  {
    title: '张',
    author: '说地方',
    status: 'all',
    date: '123',
  }, {
    title: '网',
    author: '士大夫十分',
    status: 'all',
    date: '123',
  },
  {
    title: '说地方',
    author: '给共和国和',
    status: 'all',
    date: '123',
  },
];

export const demoPdfUrl = 'https://bruink-1256854426.cos.ap-beijing.myqcloud.com/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%88%86%E7%A6%BB%E6%A1%86%E6%9E%B6%E5%9C%A8%E8%BD%AF%E4%BB%B6%E8%AE%BE%E8%AE%A1%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8_%E6%9D%8E%E5%AE%87.pdf';

